# Generated by Django 5.2.4 on 2025-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_timetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='requested_at',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requested_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
