# Generated by Django 5.2.4 on 2025-07-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_servicerequest_requested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetransaction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='timetransaction',
            name='hours',
            field=models.FloatField(),
        ),
    ]
