# Generated by Django 5.2.4 on 2025-07-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
